language: python
git:
  depth: 99999
python:
- '2.7'
- '3.5'
sudo: false
cache:
  directories:
  - "$HOME/.cache/pip"
addons:
  postgresql: '9.4'
  apt:
    packages:
    - libhdf5-serial-dev
    - libnetcdf-dev
    - libproj-dev
    - libgdal1-dev
    - libudunits2-dev
    - libblas-dev
    - liblapack-dev
    - gfortran
before_install:
- createdb agdcintegration
install:
- export CPLUS_INCLUDE_PATH="/usr/include/gdal"
- export C_INCLUDE_PATH="/usr/include/gdal"
- travis_retry pip install pylint==1.6.4 gdal==1.10.0 compliance-checker
- travis_retry pip install --upgrade pip pytest
- travis_retry pip install .[analytics,test,interactive]
script:
- "./check-code.sh integration_tests"
after_success:
- coveralls
notifications:
  slack:
    on_success: change
    on_failure: always
    on_pull_requests: false
    rooms:
      secure: ADGOG3YqqYnLq2vT+3eIVr+Gr91Zp0+6n7V4C0hZziAf2wE6fKSqk9xamWad4a96c+kGnlK7xzUuqPretcfCY3ANFnZKtqyckBnMuU+wlUvCee9nybXmqXB+hfuNSVkeVkC51yVTzsnNhj5ASDy4OdD+duGUn9gY2fgHVf2WK8V98tFmt1kviV4h2me/d1+wNLu6hmtRWGW7klpY4Oz9pP6HruFvbTh28H2VArnpiT2t8PIEsNTIZNnOQOVUtUEdecB0svFRXKqCdklVns6wlyWsPpHWZ7HuxRy8K/wutKR85EFVxWiS9jCFSjPlzYBsyQyWq1oKiDVtusIha2XtsTMq1D+3wnPH1T8yFyqD4xuFCG0mkk99hGHlgCvYLDhzYLZdj2zcTewF3Oye3oxnoaeSRcsIS7i93Z9qxdWRIh093ZUr+rQ2hw6r2SSGBLaE+9pnlkVPU+JoeGHo9PsZzPKGMyUeSkQaLuBbTc4V308uAodPfJge0+BAz2TWe6w+bOrem+QaMtInGXcuAIWjQfFpxjOjBeegatobSitTvxPjeNgRrZTjPWEqAOgBEqcRcAymKP7bI8IOFSmH5KdLE6niB0yiatWOKQu8BVSRpZ4CiPK3MyVe09x0g5HCQJZ+bEjkDnCpkKtXTBuT9U8CHzTUqxfeZ3hiEOZFWPvVOyk=
env:
  global:
  - secure: ovEn6Q/wVM5zhS/bobgSRM0/aVBTd4uuwkgAYKEQuS/2laIejx1+b+lgN8v5rK1z82O3FNafjFURgFXkWuDN37CxlzznhgyJDDhHEeTThiTnQ46Ml4/hjsGMoXo0CpChLjAhPECR3sXtV047otcrQWGEZ/EpPbv4iiqzY0nFPaqgNxLSwoK2F40l3AD5zUcB0gH3e1c4elZnlXWSFXS9fkxPeTj42sGAImkTr5yVi3RF8qHSQ+UXjREAzuLJyrVij5lwD+UbDkzyKwdsOvmfOdC9H991y0VBLcfECvV1XPhfdqTACTT8TBHJW1Fk3HddnqKSzHWD8zlA2lcCkmf3dVE+e7wnfxSID6sQKm57RgdJYEyZBhZQj8A1I7HuYjGFQL4RHybi7JdF3uHJ4bLkLoUDrNC5MUjvzlVhcoycJObb5v2WZylqAVGsfR3tTobNyT3tCfKrFX3iIVtkykZ0rvO/v72eSrjlO7DIXCnX7hOgw0z/rtUdZ6PQvUjuNvIiqdrSh81ss+OdBZheIwOmRCSGP3kV5VQDiLj3gqJ2ouiqAszUAU+x7VAVFvF/A+MWqfjtn8GW27/P3VDiFQUSMcbQ/It+OxLJ4yUi58TuflTQ3pM7ioX+LPCDrfEvHr2QVL3+hCy1kyyzWkxMHZktbpx3cRV1A21BX99bqDVojGQ=
  - secure: IaKeq9BMMbs2jTVgQRPojUmq1aZ9sSuRR3e9I0iWVQAROCAU/1tIT2Rdrvv1rATQumuST6mdH31IddF711SA9UaW7TeIuerofp97xpjazHoBFu6LMuwL3HAq9CD3RcBFDjT9YlTl1dRq0sjeqOc6XeEQxrBksNoEqUGh+b3YPIxNwUCdrbQHHuF53ee4i5/BinUjCRqzv+J/1bPBIuU94FLPK0zmD6OJXvNFWxOTTD+feFFLK7F0vlkDWdHy9Okp6We+/A+50Duh2aFVadPbe8G3VjAh2xsQSqMPZBQLFHzQD3a3KYUG+gECmbcierpJpF4LStMAxa2zFkMiiulLU5btKiCySe0fW06Ku4UjG0o7Y51Nt0q8k5RXRpVsO5+elh+ecKe3rsaDDuiHxg/MXWJpiFCfGgGy2LGtnmAYS1gEI4uitaHwS0QmIInVObS6sXH/lwFcMCoMKBinjdWCJE27ecuuhq5tFoi2ND+htxpjYMPlzf6lI/sx/RCGruUjvGgV/V4eZ3TkiVbZfL+RVilaPUHJ55m35Z9gL3OVMTSTJLJnViX1mSimpDXEZ25OraDIvzutxzk7JHMCjI9ybIIOVa+aI6UHFj4iZJLLKlPrlmTKbR4TotqX1IUjPszGkNdQS3mtS4ZJnnxAYcKytViKArRPfuRQd0nDEv9B+fI=
