language: python

python:
  - "2.7"
  - "3.5"

sudo: true

addons:
  apt:
    packages:
cache: apt

install:
  - travis_retry pip install pep8 pylint pytest pytest-cov coveralls
  - travis_retry pip install -r requirements.txt

script:
    # - pep8 eodatasets --max-line-length 120
    # - pylint eodatasets --reports no
    - py.test --cov test -m "not data"

after_success:
  coveralls
