# whitelist
branches:
  only:
    - robw_add_docs

language: python
python:
    # - "3.4"
    - "2.7"

# Travis already has postgresql installed - see addons: and  before_script: sections for configuration
addons:
  postgresql: "9.3"

# Command to install miniconda to build test environment
before_install:
  # Install required packages
  - sudo apt-get update -qq
  # This fix doesn't work for the postgis being uninstalled by gdal package dependencies.Keeping it here so I have the reference until this is resolved.
  #- sudo rm /etc/apt/sources.list.d/ubuntugis-stable-source.list # see https://github.com/travis-ci/travis-ci/issues/2401
  # HDF4, HDF5, GDAL and netCDF4
  # Note: Using libhdf4-alt-dev for compatibility with GDAL
  - sudo apt-get install -qq libhdf4-alt-dev libhdf5-serial-dev libnetcdf-dev libgdal-dev
  # Fixing postgis uninstall by gdal package problem on travis, attempt to reinstall
  - sudo apt-get install -qq postgresql-9.3-postgis-2.1
  # Python and packages
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  # Add binstar channels to get custom builds
  # Add Jess Robertson (CSIRO) binstar channel to get custom builds for some utilities
  - conda config --add channels jesserobertson
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  # Test database
  - wget https://github.com/data-cube/agdc-v2-data/raw/master/sample_dbs/gdf_modis_20150710.backup
  - wget https://github.com/data-cube/agdc-v2-data/raw/master/sample_dbs/gdf_landsat_20150710.backup

  - cd gdf_database
  - ./gdf_db_setup.sh
  - ./create_db_from_backup.sh gdf_test_modis ../gdf_modis_20150710.backup
  - ./create_db_from_backup.sh gdf_test_ls ../gdf_landsat_20150710.backup
  - cd ..

install:
  - conda create -q -n test-agdc python=$TRAVIS_PYTHON_VERSION nose pip sphinx numpy scipy matplotlib gdal netCDF4 numexpr psycopg2 coverage coveralls
  - source activate test-agdc
  - python setup.py install
  -

# Command to run tests
script:
   - coverage run -m unittest discover gdf_tests

after_success:
  - coveralls
