
name: LS7 NBAR

match:
  dataset:
    ga_level: P54
    product_type: NBAR
    platform:
      code: LANDSAT_7
    instrument:
      name: TM

storage:
    - name: foo
      bands:
        '10':
            dtype: int16
            fill_value: -999
            interpolation: nearest
        '20':
            dtype: int16
            fill_value: -999
            interpolation: cubic
    - name: bar
      bands:
        '8':
            dtype: int16
            fill_value: -999
            interpolation: linear
